name: 'Create file'
description: 'Create a file and push to specific branch'
author: 'Tien Chau'

inputs:
  file:
    description: 'File to upload'
    required: true
  owner:
    description: 'Your target owner'
  repo:
    description: 'Your target repo'
  token:
    description: 'Github personal token'
    required: true
  message:
    description: 'Your commit message'
    required: true
  path:
    description: 'Your input description here'
    required: true
  branch:
    description: 'Your target branch'
    required: true
  update-file:
    description: 'Update existed file'

runs:
  using: node20
  main: dist/index.js
